sudo: false

language: clojure

lein: lein

jdk:
  - oraclejdk8

before_script:
  - git clone https://github.com/riemann/riemann.git
  - cd riemann
  - lein deps
  - sudo lein run &
  - cd ..

cache:
  directories:
    - $HOME/.m2
