sudo: required
dist: trusty
group: edge
language: clojure
lein: lein
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

matrix:
  allow_failures:
    - jdk: oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

cache:
  directories:
    - $HOME/.m2
